name: Test-api

on:
  push:
    branches:
      - main
        
jobs:
  starts_dredd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Dredd
        run: |
          npm install -g dredd
          cd dredd
          dredd init -r apiary -j apiaryApiKey:${{ secrets.APIARYAPIKEY }} -j apiaryApiName:${{ secrets.APIARYAPINAME }}
  
